// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAc9EN7gvUsfzosMSAcWUU5bhOt-_NdhwY',
    appId: '1:359850736203:web:6571ffec008d1e28cd2bce',
    messagingSenderId: '359850736203',
    projectId: 'spotify-reprise-carnell',
    authDomain: 'spotify-reprise-carnell.firebaseapp.com',
    storageBucket: 'spotify-reprise-carnell.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJ-E-qABsY5qUTYTrlcgp7qa37Vy4UZ60',
    appId: '1:359850736203:android:9e0fa24a3a629c1fcd2bce',
    messagingSenderId: '359850736203',
    projectId: 'spotify-reprise-carnell',
    storageBucket: 'spotify-reprise-carnell.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADlNsoXhbU4uLlubYomLkxhjRi7gc6WjA',
    appId: '1:359850736203:ios:3651fe4500d5ed24cd2bce',
    messagingSenderId: '359850736203',
    projectId: 'spotify-reprise-carnell',
    storageBucket: 'spotify-reprise-carnell.firebasestorage.app',
    iosBundleId: 'com.example.spotifyReprise',
  );
}
